#!/bin/bash

# Test script to verify news display with publication details

echo "Testing news display with publication IDs..."
echo "========================================="
echo ""
echo "To test the changes, run:"
echo "  jekyll serve"
echo ""
echo "Then check:"
echo "- English page: http://localhost:4000/"
echo "- Japanese page: http://localhost:4000/japanese.html"
echo ""
echo "What has been implemented:"
echo "1. Added 'id' field to publications in publications.yaml"
echo "2. News items can now reference publications using 'publication_id' in detail array"
echo "3. When a publication_id is used, the system will display:"
echo "   - Paper title (in italic)"
echo "   - Authors below the title (smaller font, indented)"
echo ""
echo "Example usage in news.yaml or news_ja.yaml:"
echo "  detail:"
echo "    - publication_id: \"miru2025-multimodal\""
echo ""
echo "The following publication IDs are available:"
echo "  - miru2025-vl-qa"
echo "  - miru2025-multimodal"
echo "  - medai2025-discharge"
echo "  - nlp2025-asagi"
echo "  - ipsj2025-med-nlp"
echo "  - nl2025-medical"
echo "  - aaai2024-wikisqe"
echo ""